safe: false
source: .
destination: ./_site
plugins_dir: ./_plugin
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache', '.asset-cache']

plugins:
  - jekyll-assets

title: "TCN-6430: Networks Management and Control Standards"
description: Fall 2020 (Florida International University)
author: Alex Afanasyev

baseurl: "/~afanasyev/classes/fall20/TCN-6430"
url: "https://users.cs.fiu.edu"

timezone: America/New_York

spreadsheets:
  google_client_id: _data/google-id.json
  spreadsheet:
    - "1vED9eSN8j-iFRZ5xDHfhR8X83l1SFGDqcyHZLM9Bbx0"

assets:
  cache: .sass-cache

  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
